import React, { useState } from 'react';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View, useWindowDimensions } from 'react-native';
import DashboardScreen from '../screens/Dashboard';
import IncomeScreen from '../screens/Income';
import ExpenseScreen from '../screens/Expense';
import NotificationsScreen from '../screens/Notifications';
import ProfileScreen from '../screens/Profile';
import SettingsScreen from '../screens/Settings';
import { useFinance } from '../context/FinanceContext';
import { RootStackParamList } from '../types';

type Page = 'Dashboard' | 'Income' | 'Expenses' | 'Notifications' | 'Profile' | 'Settings';
type Props = { navigation: NativeStackNavigationProp<RootStackParamList, 'Main'> };
const primaryItems: { page: Page; icon: string; label: string }[] = [
  { page: 'Dashboard', icon: '▦', label: 'Dashboard' },
  { page: 'Income', icon: '↗', label: 'Income' },
  { page: 'Expenses', icon: '↘', label: 'Expenses' },
  { page: 'Notifications', icon: '◌', label: 'Notifications' },
];

export default function MainShell({ navigation }: Props) {
  const [page, setPage] = useState<Page>('Dashboard');
  const [collapsed, setCollapsed] = useState(false);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [search, setSearch] = useState('');
  const { user, notifications, theme } = useFinance();
  const mobile = useWindowDimensions().width < 600;
  const dark = theme === 'dark';
  const go = (nextPage: Page) => { setPage(nextPage); if (mobile) setDrawerOpen(false); };
  const content = page === 'Dashboard' ? <DashboardScreen /> : page === 'Income' ? <IncomeScreen /> : page === 'Expenses' ? <ExpenseScreen /> : page === 'Notifications' ? <NotificationsScreen /> : page === 'Profile' ? <ProfileScreen /> : <SettingsScreen />;
  const logout = () => navigation.reset({ index: 0, routes: [{ name: 'Login' }] });
  const sidebar = <View style={[styles.sidebar, dark && styles.darkSurface, mobile && styles.mobileDrawer, !mobile && collapsed && styles.sidebarCollapsed]}><View style={styles.brandRow}><View style={styles.logo}><Text style={styles.logoText}>PF</Text></View>{(!collapsed || mobile) && <View><Text style={[styles.brand, dark && styles.darkText]}>PFMS</Text><Text style={styles.brandSub}>Personal Finance</Text></View>}</View><View style={styles.nav}>{primaryItems.map((item) => <TouchableOpacity key={item.page} onPress={() => go(item.page)} style={[styles.navItem, page === item.page && styles.navActive]} accessibilityLabel={item.label}><Text style={[styles.navIcon, page === item.page && styles.navIconActive]}>{item.icon}</Text>{(!collapsed || mobile) && <Text style={[styles.navText, page === item.page && styles.navTextActive]}>{item.label}</Text>}</TouchableOpacity>)}</View><View style={styles.bottomNav}><TouchableOpacity onPress={() => go('Profile')} style={[styles.navItem, page === 'Profile' && styles.navActive]} accessibilityLabel="Profile"><Text style={styles.navIcon}>◉</Text>{(!collapsed || mobile) && <Text style={styles.navText}>Profile</Text>}</TouchableOpacity><TouchableOpacity onPress={() => go('Settings')} style={[styles.navItem, page === 'Settings' && styles.navActive]} accessibilityLabel="Settings"><Text style={styles.navIcon}>⚙</Text>{(!collapsed || mobile) && <Text style={styles.navText}>Settings</Text>}</TouchableOpacity><TouchableOpacity onPress={logout} style={styles.navItem} accessibilityLabel="Logout"><Text style={styles.navIcon}>↪</Text>{(!collapsed || mobile) && <Text style={styles.navText}>Logout</Text>}</TouchableOpacity></View></View>;

  return <SafeAreaView style={[styles.root, dark && styles.darkRoot]}><View style={styles.app}>{!mobile && sidebar}{mobile && drawerOpen && <><TouchableOpacity style={styles.drawerBackdrop} onPress={() => setDrawerOpen(false)} accessibilityLabel="Close menu" /><View style={styles.drawerLayer}>{sidebar}</View></>}<View style={styles.main}><View style={[styles.header, dark && styles.darkSurface, mobile && styles.mobileHeader]}><View style={styles.headerLeft}><TouchableOpacity onPress={() => mobile ? setDrawerOpen((value) => !value) : setCollapsed((value) => !value)} style={styles.menu} accessibilityLabel={mobile ? 'Open menu' : 'Toggle sidebar'}><Text style={styles.menuText}>☰</Text></TouchableOpacity><Text style={[styles.pageTitle, dark && styles.darkText]}>{page}</Text></View><View style={styles.headerRight}>{!mobile && <TextInput value={search} onChangeText={setSearch} style={[styles.search, dark && styles.darkInput]} placeholder="Search" placeholderTextColor="#94a3b8" />}{!mobile && <Text style={[styles.userName, dark && styles.darkText]}>{user.name}</Text>}<TouchableOpacity onPress={() => go('Notifications')} style={styles.bell} accessibilityLabel="Notifications"><Text style={styles.bellText}>◌</Text>{notifications.some((item) => !item.read) && <View style={styles.badge} />}</TouchableOpacity><TouchableOpacity onPress={() => go('Profile')} style={styles.user} accessibilityLabel="Profile"><View style={styles.userAvatar}><Text style={styles.userInitial}>{user.name.charAt(0)}</Text></View></TouchableOpacity></View></View><View style={styles.body}>{content}</View></View></View></SafeAreaView>;
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f5f6f8' }, darkRoot: { backgroundColor: '#0f172a' }, app: { flex: 1, flexDirection: 'row', position: 'relative' },
  sidebar: { width: 248, backgroundColor: '#fff', borderRightWidth: 1, borderRightColor: '#e6eaf0', paddingHorizontal: 18, paddingVertical: 24 }, sidebarCollapsed: { width: 52, paddingHorizontal: 4, paddingVertical: 14 }, mobileDrawer: { width: 260, height: '100%', borderRightWidth: 0, shadowColor: '#0f172a', shadowOpacity: .2, shadowRadius: 18, shadowOffset: { width: 8, height: 0 }, elevation: 12 }, drawerLayer: { position: 'absolute', top: 0, bottom: 0, left: 0, zIndex: 20 }, drawerBackdrop: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, zIndex: 10, backgroundColor: 'rgba(15, 23, 42, .42)' }, darkSurface: { backgroundColor: '#111c31', borderColor: '#263653' }, brandRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 8, marginBottom: 42 }, logo: { width: 38, height: 38, borderRadius: 11, backgroundColor: '#14213d', alignItems: 'center', justifyContent: 'center' }, logoText: { color: '#fff', fontWeight: '800', fontSize: 14 }, brand: { color: '#14213d', fontWeight: '900', fontSize: 17 }, brandSub: { color: '#94a3b8', fontSize: 10, marginTop: 2 }, nav: { gap: 7 }, navItem: { flexDirection: 'row', alignItems: 'center', gap: 13, paddingVertical: 12, paddingHorizontal: 12, borderRadius: 9 }, navActive: { backgroundColor: '#edf3ff' }, navIcon: { color: '#64748b', width: 20, textAlign: 'center', fontSize: 17 }, navIconActive: { color: '#4f7cff' }, navText: { color: '#64748b', fontSize: 13, fontWeight: '600' }, navTextActive: { color: '#315dcc', fontWeight: '800' }, bottomNav: { marginTop: 'auto', gap: 7 }, main: { flex: 1, minWidth: 0 }, header: { minHeight: 76, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#e6eaf0', paddingHorizontal: 28, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 16 }, mobileHeader: { minHeight: 60, paddingHorizontal: 10, gap: 6 }, headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 15, flexShrink: 1 }, menu: { padding: 5 }, menuText: { color: '#64748b', fontSize: 20 }, pageTitle: { color: '#14213d', fontSize: 20, fontWeight: '800' }, darkText: { color: '#f8fafc' }, headerRight: { flexDirection: 'row', alignItems: 'center', gap: 8, flexShrink: 1 }, search: { width: 190, height: 38, backgroundColor: '#f5f6f8', borderRadius: 9, paddingHorizontal: 13, color: '#14213d', fontSize: 13 }, darkInput: { backgroundColor: '#1e293b', color: '#f8fafc' }, userName: { color: '#334155', fontSize: 13, fontWeight: '700' }, bell: { position: 'relative', padding: 7 }, bellText: { color: '#64748b', fontSize: 22 }, badge: { position: 'absolute', top: 4, right: 3, width: 7, height: 7, borderRadius: 5, backgroundColor: '#ef6b6b' }, user: { flexDirection: 'row', alignItems: 'center' }, userAvatar: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#dbe4ff', alignItems: 'center', justifyContent: 'center' }, userInitial: { color: '#315dcc', fontWeight: '800' }, body: { flex: 1, minWidth: 0 },
});
