import React, { useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFinance } from '../context/FinanceContext';

const ExpenseScreen: React.FC = () => {
  const { expenses, setExpenses } = useFinance();
  const [open, setOpen] = useState(false);
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState('Food');
  const total = expenses.reduce((sum, item) => sum + item.amount, 0);
  const addExpense = () => { if (!description.trim() || !amount.trim()) return; setExpenses((items) => [{ id: Date.now(), description: description.trim(), category: category.trim() || 'Other', amount: Number(amount), date: new Date().toISOString().slice(0, 10) }, ...items]); setDescription(''); setAmount(''); setOpen(false); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.titleRow}><View><Text style={styles.heading}>Expenses</Text><Text style={styles.subtitle}>See where your money is going.</Text></View><TouchableOpacity style={styles.action} onPress={() => setOpen(true)}><Text style={styles.actionText}>＋ Add Expense</Text></TouchableOpacity></View><View style={styles.totalCard}><Text style={styles.totalLabel}>Total expenses</Text><Text style={styles.totalValue}>{total.toLocaleString()} ETB</Text><Text style={styles.totalMeta}>{expenses.length} expense entries</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Expense transactions</Text>{expenses.length === 0 ? <Text style={styles.empty}>No expense entries yet.</Text> : expenses.map((item) => <View key={item.id} style={styles.row}><View style={styles.rowIcon}><Text style={styles.iconText}>↘</Text></View><View style={styles.rowMain}><Text style={styles.rowTitle}>{item.description}</Text><Text style={styles.rowMeta}>{item.category} · {item.date}</Text></View><Text style={styles.amount}>-{item.amount.toLocaleString()} ETB</Text><TouchableOpacity onPress={() => setExpenses((items) => items.filter((entry) => entry.id !== item.id))}><Text style={styles.delete}>Delete</Text></TouchableOpacity></View>)}</View><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><View style={styles.overlay}><View style={styles.modal}><View style={styles.modalHeader}><Text style={styles.modalTitle}>Add expense</Text><TouchableOpacity onPress={() => setOpen(false)}><Text style={styles.close}>×</Text></TouchableOpacity></View><Text style={styles.label}>Description</Text><TextInput style={styles.input} value={description} onChangeText={setDescription} placeholder="Groceries, rent, transport..." placeholderTextColor="#94a3b8" autoFocus /><Text style={styles.label}>Amount</Text><TextInput style={styles.input} value={amount} onChangeText={setAmount} placeholder="0.00" keyboardType="numeric" placeholderTextColor="#94a3b8" /><Text style={styles.label}>Category</Text><TextInput style={styles.input} value={category} onChangeText={setCategory} placeholder="Category" placeholderTextColor="#94a3b8" /><View style={styles.modalActions}><TouchableOpacity style={styles.cancel} onPress={() => setOpen(false)}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity><TouchableOpacity style={styles.save} onPress={addExpense}><Text style={styles.saveText}>Save expense</Text></TouchableOpacity></View></View></View></Modal></ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f5f6f8' }, content: { padding: 28, gap: 18 }, titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 }, heading: { fontSize: 28, fontWeight: '800', color: '#14213d' }, subtitle: { color: '#718096', marginTop: 5 }, action: { backgroundColor: '#14213d', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 10 }, actionText: { color: '#fff', fontWeight: '700' }, totalCard: { backgroundColor: '#fff5f5', borderColor: '#ffd9d9', borderWidth: 1, borderRadius: 14, padding: 22 }, totalLabel: { color: '#ad5d5d', fontWeight: '600' }, totalValue: { color: '#14213d', fontSize: 30, fontWeight: '800', marginTop: 6 }, totalMeta: { color: '#a98585', fontSize: 12, marginTop: 5 }, card: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e6eaf0', borderRadius: 14, padding: 22 }, cardTitle: { color: '#14213d', fontSize: 17, fontWeight: '800', marginBottom: 14 }, row: { minHeight: 66, borderTopWidth: 1, borderTopColor: '#f0f2f5', flexDirection: 'row', alignItems: 'center', gap: 12 }, rowIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: '#fff0f0', alignItems: 'center', justifyContent: 'center' }, iconText: { color: '#ef6b6b', fontWeight: '800' }, rowMain: { flex: 1 }, rowTitle: { color: '#14213d', fontWeight: '700' }, rowMeta: { color: '#94a3b8', fontSize: 12, marginTop: 4 }, amount: { color: '#ef6b6b', fontWeight: '800' }, delete: { color: '#94a3b8', fontSize: 11 }, empty: { color: '#94a3b8', paddingVertical: 20 }, overlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, .45)', alignItems: 'center', justifyContent: 'center', padding: 20 }, modal: { width: '100%', maxWidth: 460, backgroundColor: '#fff', borderRadius: 16, padding: 24, gap: 9, shadowColor: '#0f172a', shadowOpacity: .18, shadowRadius: 24, shadowOffset: { width: 0, height: 12 }, elevation: 10 }, modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }, modalTitle: { color: '#14213d', fontSize: 20, fontWeight: '800' }, close: { color: '#64748b', fontSize: 28, lineHeight: 28 }, label: { color: '#475569', fontSize: 12, fontWeight: '700', marginTop: 4 }, input: { borderWidth: 1, borderColor: '#dfe5ed', borderRadius: 9, paddingHorizontal: 12, paddingVertical: 12, color: '#14213d', fontSize: 14 }, modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 10 }, cancel: { borderWidth: 1, borderColor: '#dfe5ed', borderRadius: 9, paddingHorizontal: 16, paddingVertical: 12 }, cancelText: { color: '#64748b', fontWeight: '700' }, save: { backgroundColor: '#ef6b6b', borderRadius: 9, paddingHorizontal: 16, paddingVertical: 12 }, saveText: { color: '#fff', fontWeight: '800' } });
export default ExpenseScreen;
