import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View, useWindowDimensions } from 'react-native';
import { useNotifications } from '../context/NotificationContext';

const NotificationsScreen: React.FC = () => {
  const { notifications, markRead, markAllRead } = useNotifications();
  const mobile = useWindowDimensions().width < 600;
  const unread = notifications.filter((item) => !item.read).length;
  return <ScrollView style={styles.page} contentContainerStyle={[styles.content, mobile && styles.mobileContent]}><View style={[styles.titleRow, mobile && styles.mobileTitleRow]}><View><Text style={styles.heading}>Notifications</Text><Text style={styles.subtitle}>{unread ? `${unread} unread updates` : 'You are all caught up'}</Text></View>{unread > 0 && <TouchableOpacity onPress={markAllRead}><Text style={styles.mark}>Mark all as read</Text></TouchableOpacity>}</View><View style={styles.card}>{notifications.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>You're all caught up</Text><Text style={styles.emptyText}>New reminders and alerts will appear here.</Text></View> : notifications.map((item) => <TouchableOpacity key={item.id} onPress={() => markRead(item.id)} activeOpacity={0.75} style={[styles.row, !item.read && styles.unread]}><View style={[styles.icon, item.type === 'warning' ? styles.yellow : item.type === 'exceeded' ? styles.red : styles.blue]}><Text style={styles.iconText}>{item.type === 'warning' ? '!' : item.type === 'exceeded' ? '×' : 'i'}</Text></View><View style={styles.main}><View style={styles.titleLine}><Text style={styles.itemTitle}>{item.title}</Text>{!item.read && <View style={styles.unreadDot} />}</View><Text style={styles.message}>{item.message}</Text><Text style={styles.time}>{item.time} · {item.read ? 'Read' : 'Tap to mark as read'}</Text></View></TouchableOpacity>)}</View></ScrollView>;
};
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f5f6f8' }, content: { padding: 28, gap: 18 }, mobileContent: { padding: 16, gap: 14 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 }, mobileTitleRow: { alignItems: 'flex-start', flexDirection: 'column', gap: 10 }, heading: { fontSize: 28, fontWeight: '800', color: '#14213d' }, subtitle: { color: '#718096', marginTop: 5 }, mark: { color: '#4f7cff', fontSize: 13, fontWeight: '700' }, card: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e6eaf0', borderRadius: 14, padding: 20 }, row: { flexDirection: 'row', gap: 14, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#f0f2f5', minHeight: 64 }, unread: { backgroundColor: '#fbfcff' }, icon: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, yellow: { backgroundColor: '#fff4cd' }, red: { backgroundColor: '#ffe2e2' }, blue: { backgroundColor: '#e6efff' }, iconText: { color: '#475569', fontWeight: '800', fontSize: 16 }, main: { flex: 1, minWidth: 0 }, titleLine: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' }, itemTitle: { color: '#14213d', fontWeight: '800', flexShrink: 1 }, unreadDot: { width: 7, height: 7, borderRadius: 5, backgroundColor: '#4f7cff' }, message: { color: '#64748b', fontSize: 13, marginTop: 5 }, time: { color: '#94a3b8', fontSize: 11, marginTop: 8 }, empty: { alignItems: 'center', padding: 42 }, emptyTitle: { color: '#14213d', fontSize: 17, fontWeight: '800' }, emptyText: { color: '#94a3b8', marginTop: 6 } });
export default NotificationsScreen;
