import React, { useState } from 'react';
import { Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFinance } from '../context/FinanceContext';

const ProfileScreen: React.FC = () => {
  const { user, setUser } = useFinance();
  const [editing, setEditing] = useState(false);
  const [name, setName] = useState(user.name);
  const [email, setEmail] = useState(user.email);
  const [phone, setPhone] = useState(user.phone);
  const [currency, setCurrency] = useState(user.currency);
  const [error, setError] = useState('');
  const save = () => { if (!name.trim() || !email.trim() || !/\S+@\S+\.\S+/.test(email)) { setError('Enter a name and a valid email address.'); return; } setUser((current) => ({ ...current, name: name.trim(), email: email.trim(), phone: phone.trim(), currency: currency.trim() || 'ETB' })); setError(''); setEditing(false); };
  const openEditor = () => { setName(user.name); setEmail(user.email); setPhone(user.phone); setCurrency(user.currency); setError(''); setEditing(true); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.heading}>Profile</Text><Text style={styles.subtitle}>Manage your personal and account information.</Text><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.charAt(0)}</Text></View><View style={styles.identity}><Text style={styles.name}>{user.name}</Text><Text style={styles.email}>{user.email}</Text><Text style={styles.member}>Member since {user.memberSince}</Text></View><TouchableOpacity style={styles.edit} onPress={openEditor}><Text style={styles.editText}>Edit Profile</Text></TouchableOpacity></View><View style={styles.card}><Text style={styles.cardTitle}>Personal details</Text><Info label="Full name" value={user.name} /><Info label="Email" value={user.email} /><Info label="Phone" value={user.phone} /><Info label="Currency" value={user.currency} /></View><View style={styles.card}><Text style={styles.cardTitle}>Account status</Text><Info label="Member since" value={user.memberSince} /><Info label="Budget alerts" value={user.budgetAlerts ? 'Enabled' : 'Disabled'} /><Text style={styles.accountNote}>Security and notification preferences are managed from Settings.</Text></View><Modal visible={editing} transparent animationType="fade" onRequestClose={() => setEditing(false)}><View style={styles.overlay}><View style={styles.modal}><View style={styles.modalHeader}><Text style={styles.modalTitle}>Edit profile</Text><TouchableOpacity onPress={() => setEditing(false)}><Text style={styles.close}>×</Text></TouchableOpacity></View><Field label="Full name" value={name} onChangeText={setName} /><Field label="Email" value={email} onChangeText={setEmail} keyboardType="email-address" /><Field label="Phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /><Field label="Currency" value={currency} onChangeText={setCurrency} />{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.actions}><TouchableOpacity style={styles.cancel} onPress={() => setEditing(false)}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity><TouchableOpacity style={styles.save} onPress={save}><Text style={styles.saveText}>Save changes</Text></TouchableOpacity></View></View></View></Modal></ScrollView>;
};
const Field = ({ label, value, onChangeText, keyboardType }: { label: string; value: string; onChangeText: (value: string) => void; keyboardType?: 'email-address' | 'phone-pad' }) => <View><Text style={styles.formLabel}>{label}</Text><TextInput value={value} onChangeText={onChangeText} keyboardType={keyboardType} style={styles.input} placeholderTextColor="#94a3b8" /></View>;
const Info = ({ label, value }: { label: string; value: string }) => <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>;
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f5f6f8' }, content: { padding: 28, gap: 18 }, heading: { color: '#14213d', fontSize: 28, fontWeight: '800' }, subtitle: { color: '#718096', marginTop: -10 }, profileCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e6eaf0', padding: 22 }, avatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#14213d', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#fff', fontSize: 24, fontWeight: '800' }, identity: { flex: 1 }, name: { color: '#14213d', fontSize: 17, fontWeight: '800' }, email: { color: '#64748b', fontSize: 13, marginTop: 4 }, member: { color: '#94a3b8', fontSize: 11, marginTop: 5 }, edit: { borderColor: '#dbe4ff', borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9 }, editText: { color: '#4f7cff', fontWeight: '700', fontSize: 12 }, card: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e6eaf0', padding: 22 }, cardTitle: { color: '#14213d', fontSize: 16, fontWeight: '800', marginBottom: 10 }, info: { flexDirection: 'row', justifyContent: 'space-between', gap: 20, paddingVertical: 13, borderTopWidth: 1, borderTopColor: '#f0f2f5' }, label: { color: '#64748b', fontSize: 13 }, value: { color: '#14213d', fontSize: 13, fontWeight: '700', flexShrink: 1 }, accountNote: { color: '#94a3b8', fontSize: 12, marginTop: 12 }, overlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, .45)', alignItems: 'center', justifyContent: 'center', padding: 20 }, modal: { width: '100%', maxWidth: 440, backgroundColor: '#fff', borderRadius: 16, padding: 24, gap: 9 }, modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, modalTitle: { color: '#14213d', fontSize: 20, fontWeight: '800' }, close: { color: '#64748b', fontSize: 28 }, formLabel: { color: '#475569', fontSize: 12, fontWeight: '700', marginTop: 8 }, input: { borderWidth: 1, borderColor: '#dfe5ed', borderRadius: 9, padding: 12, color: '#14213d' }, error: { color: '#dc6262', fontSize: 12 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, marginTop: 12 }, cancel: { borderWidth: 1, borderColor: '#dfe5ed', borderRadius: 9, padding: 12 }, cancelText: { color: '#64748b', fontWeight: '700' }, save: { backgroundColor: '#4f7cff', borderRadius: 9, padding: 12 }, saveText: { color: '#fff', fontWeight: '800' } });
export default ProfileScreen;
