import React from 'react';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFinance } from '../context/FinanceContext';

const ProfileScreen: React.FC = () => {
  const { user } = useFinance();
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.heading}>Profile</Text><Text style={styles.subtitle}>Manage your account and preferences.</Text><View style={styles.profileCard}><View style={styles.avatar}><Text style={styles.avatarText}>{user.name.charAt(0)}</Text></View><View><Text style={styles.name}>{user.name}</Text><Text style={styles.email}>{user.email}</Text><Text style={styles.member}>Member since {user.memberSince}</Text></View><TouchableOpacity style={styles.edit}><Text style={styles.editText}>Edit Profile</Text></TouchableOpacity></View><View style={styles.card}><Text style={styles.cardTitle}>Account information</Text><Info label="Phone" value={user.phone} /><Info label="Currency" value={user.currency} /><Info label="Budget alerts" value={user.budgetAlerts ? 'Enabled' : 'Disabled'} /></View><View style={styles.card}><Text style={styles.cardTitle}>Settings</Text><TouchableOpacity style={styles.setting}><Text style={styles.settingTitle}>Change Password</Text><Text style={styles.arrow}>›</Text></TouchableOpacity><TouchableOpacity style={styles.setting}><Text style={styles.settingTitle}>Notification Settings</Text><Text style={styles.arrow}>›</Text></TouchableOpacity><TouchableOpacity style={styles.setting}><Text style={styles.settingTitle}>Theme & Appearance</Text><Text style={styles.settingValue}>Light</Text></TouchableOpacity></View><TouchableOpacity style={styles.logout}><Text style={styles.logoutText}>Log out</Text></TouchableOpacity></ScrollView>;
};
const Info = ({ label, value }: { label: string; value: string }) => <View style={styles.info}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>;
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: '#f5f6f8' }, content: { padding: 28, gap: 18 }, heading: { color: '#14213d', fontSize: 28, fontWeight: '800' }, subtitle: { color: '#718096', marginTop: -10 }, profileCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e6eaf0', padding: 22 }, avatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#14213d', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#fff', fontSize: 24, fontWeight: '800' }, name: { color: '#14213d', fontSize: 17, fontWeight: '800' }, email: { color: '#64748b', fontSize: 13, marginTop: 4 }, member: { color: '#94a3b8', fontSize: 11, marginTop: 5 }, edit: { marginLeft: 'auto', borderColor: '#dbe4ff', borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9 }, editText: { color: '#4f7cff', fontWeight: '700', fontSize: 12 }, card: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e6eaf0', padding: 22 }, cardTitle: { color: '#14213d', fontSize: 16, fontWeight: '800', marginBottom: 10 }, info: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 13, borderTopWidth: 1, borderTopColor: '#f0f2f5' }, label: { color: '#64748b', fontSize: 13 }, value: { color: '#14213d', fontSize: 13, fontWeight: '700' }, setting: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderTopWidth: 1, borderTopColor: '#f0f2f5' }, settingTitle: { color: '#334155', fontSize: 14, fontWeight: '600' }, arrow: { color: '#94a3b8', fontSize: 24 }, settingValue: { color: '#64748b', fontSize: 13 }, logout: { backgroundColor: '#fff', borderColor: '#ffd5d5', borderWidth: 1, borderRadius: 10, alignItems: 'center', padding: 14 }, logoutText: { color: '#e15e5e', fontWeight: '800' } });
export default ProfileScreen;
